services:
  postgres:
    image: postgres:18
    container_name: postgres
    restart: unless-stopped

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=viaviavia
      - POSTGRES_DB=ExamPlanner
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  api:
    build:
      context: ./Server
      dockerfile: ExamPlannerServer/Dockerfile

    container_name: exam_planner_api
    restart: unless-stopped

    ports:
      - "8080:8080"

    environment:
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=ExamPlanner;Username=postgres;Password=viaviavia"

    depends_on:
      - postgres

volumes:
  postgres_data:
