FROM mcr.microsoft.com/dotnet/sdk:10.0

WORKDIR /Server

COPY . .

RUN dotnet restore DatabaseConnection/DatabaseConnection.csproj
RUN dotnet restore ExamPlannerServer/ExamPlannerServer.csproj

RUN dotnet tool install --global dotnet-ef --version 10.0.11

ENV PATH="$PATH:/root/.dotnet/tools"

ENTRYPOINT ["dotnet", "ef", "migrations", "initial", "--project", "/Server/DatabaseConnection/DatabaseConnection.csproj", "--startup-project", "/Server/ExamPlannerServer/ExamPlannerServer.csproj"]

ENTRYPOINT ["dotnet", "ef", "database", "update", "--project", "/Server/DatabaseConnection/DatabaseConnection.csproj", "--startup-project", "/Server/ExamPlannerServer/ExamPlannerServer.csproj"]