@ExamPlannerServer_HostAddress = http://localhost:5145
GET {{ExamPlannerServer_HostAddress}}/api/courses

###

PATCH {{ExamPlannerServer_HostAddress}}/api/courses/1
Content-Type: application/json

{
  "notes": "test note"
}