// <auto-generated />
using System;
using DatabaseConnection.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DatabaseConnection.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261008121615_updatedDatabaseRelation")]
    partial class updatedDatabaseRelation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DatabaseConnection.model.AssessmentEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("integer");

                    b.Property<int>("ExamType")
                        .HasColumnType("integer");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PlanningElementId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("PlanningElementId")
                        .IsUnique();

                    b.ToTable("AssessmentEvent");
                });

            modelBuilder.Entity("DatabaseConnection.model.AssessmentHandIn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AssessmentEventId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("HandInDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Part")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AssessmentEventId");

                    b.ToTable("AssessmentHandIn");
                });

            modelBuilder.Entity("DatabaseConnection.model.Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClassCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CourseId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Class");
                });

            modelBuilder.Entity("DatabaseConnection.model.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ETCS")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PriorityTier")
                        .HasColumnType("integer");

                    b.Property<int>("Semester")
                        .HasColumnType("integer");

                    b.Property<string>("SueCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Course");
                });

            modelBuilder.Entity("DatabaseConnection.model.Enrollment", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.Property<int>("CourseId")
                        .HasColumnType("integer");

                    b.HasKey("StudentId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("Enrollment");
                });

            modelBuilder.Entity("DatabaseConnection.model.ExamDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ExamDayType")
                        .HasColumnType("integer");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("integer");

                    b.Property<bool>("Usable")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ScheduleId");

                    b.ToTable("ExamDay");
                });

            modelBuilder.Entity("DatabaseConnection.model.ExamSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AsseessmentId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<bool>("LockDate")
                        .HasColumnType("boolean");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AsseessmentId");

                    b.HasIndex("RoomId");

                    b.HasIndex("ScheduleId");

                    b.ToTable("ExamSession");
                });

            modelBuilder.Entity("DatabaseConnection.model.PlanningEducationElement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ActivityOffering")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("AssessmenType")
                        .HasColumnType("integer");

                    b.Property<bool>("CombinedWrittenOral")
                        .HasColumnType("boolean");

                    b.Property<bool>("CompletionAssesment")
                        .HasColumnType("boolean");

                    b.Property<int>("ECTS")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<int>("ExecutionElementCount")
                        .HasColumnType("integer");

                    b.Property<string>("GradingScale")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nickmane")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Oral")
                        .HasColumnType("boolean");

                    b.Property<bool>("PracticalExam")
                        .HasColumnType("boolean");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Project")
                        .HasColumnType("boolean");

                    b.Property<string>("SourceChecksum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SourceModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<bool>("Written")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("PlanningEducationElement");
                });

            modelBuilder.Entity("DatabaseConnection.model.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Room");
                });

            modelBuilder.Entity("DatabaseConnection.model.Schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Approved")
                        .HasColumnType("boolean");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Schedule");
                });

            modelBuilder.Entity("DatabaseConnection.model.ScheduleReview", b =>
                {
                    b.Property<int>("ScheduleId")
                        .HasColumnType("integer");

                    b.Property<int>("TeacherId")
                        .HasColumnType("integer");

                    b.Property<bool>("Approved")
                        .HasColumnType("boolean");

                    b.Property<bool>("Completed")
                        .HasColumnType("boolean");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ScheduleId", "TeacherId");

                    b.HasIndex("TeacherId");

                    b.ToTable("ScheduleReview");
                });

            modelBuilder.Entity("DatabaseConnection.model.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Student");
                });

            modelBuilder.Entity("DatabaseConnection.model.StudentExamAssignment", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.Property<int>("ExamSessionId")
                        .HasColumnType("integer");

                    b.Property<bool>("ExtraTime")
                        .HasColumnType("boolean");

                    b.HasKey("StudentId", "ExamSessionId");

                    b.HasIndex("ExamSessionId");

                    b.ToTable("StudentExamAssignment");
                });

            modelBuilder.Entity("DatabaseConnection.model.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Teacher");
                });

            modelBuilder.Entity("DatabaseConnection.model.TeacherAssignment", b =>
                {
                    b.Property<int>("ExamSessionId")
                        .HasColumnType("integer");

                    b.Property<int>("TeacherId")
                        .HasColumnType("integer");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("ExamSessionId", "TeacherId");

                    b.HasIndex("TeacherId");

                    b.ToTable("TeacherAssignment");
                });

            modelBuilder.Entity("DatabaseConnection.model.TeacherConstraint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("ConstraintDate")
                        .HasColumnType("date");

                    b.Property<int>("ConstraintType")
                        .HasColumnType("integer");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TeacherId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.ToTable("TeacherConstraint");
                });

            modelBuilder.Entity("DatabaseConnection.model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("DatabaseConnection.model.AssessmentEvent", b =>
                {
                    b.HasOne("DatabaseConnection.model.Course", "Course")
                        .WithMany("AssessmentEvents")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DatabaseConnection.model.PlanningEducationElement", "PlanningEducationElement")
                        .WithOne("AssessmentEvent")
                        .HasForeignKey("DatabaseConnection.model.AssessmentEvent", "PlanningElementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("PlanningEducationElement");
                });

            modelBuilder.Entity("DatabaseConnection.model.AssessmentHandIn", b =>
                {
                    b.HasOne("DatabaseConnection.model.AssessmentEvent", "AssessmentEvent")
                        .WithMany("AssessmentHandIns")
                        .HasForeignKey("AssessmentEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssessmentEvent");
                });

            modelBuilder.Entity("DatabaseConnection.model.Class", b =>
                {
                    b.HasOne("DatabaseConnection.model.Course", "Course")
                        .WithMany("Classes")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("DatabaseConnection.model.Enrollment", b =>
                {
                    b.HasOne("DatabaseConnection.model.Course", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DatabaseConnection.model.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("DatabaseConnection.model.ExamDay", b =>
                {
                    b.HasOne("DatabaseConnection.model.Schedule", "Schedule")
                        .WithMany("ExamDays")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("DatabaseConnection.model.ExamSession", b =>
                {
                    b.HasOne("DatabaseConnection.model.AssessmentEvent", "AssessmentEvent")
                        .WithMany("ExamSessions")
                        .HasForeignKey("AsseessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DatabaseConnection.model.Room", "Room")
                        .WithMany("ExamSessions")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DatabaseConnection.model.Schedule", "Schedule")
                        .WithMany("ExamSessions")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssessmentEvent");

                    b.Navigation("Room");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("DatabaseConnection.model.ScheduleReview", b =>
                {
                    b.HasOne("DatabaseConnection.model.Schedule", "Schedule")
                        .WithMany("ScheduleReviews")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DatabaseConnection.model.Teacher", "Teacher")
                        .WithMany("ScheduleReviewss")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Schedule");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("DatabaseConnection.model.Student", b =>
                {
                    b.HasOne("DatabaseConnection.model.User", "User")
                        .WithOne("Student")
                        .HasForeignKey("DatabaseConnection.model.Student", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DatabaseConnection.model.StudentExamAssignment", b =>
                {
                    b.HasOne("DatabaseConnection.model.ExamSession", "ExamSession")
                        .WithMany("StudentExamAssignments")
                        .HasForeignKey("ExamSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DatabaseConnection.model.Student", "Student")
                        .WithMany("StudentExamAssignment")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExamSession");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("DatabaseConnection.model.Teacher", b =>
                {
                    b.HasOne("DatabaseConnection.model.User", "User")
                        .WithOne("Teacher")
                        .HasForeignKey("DatabaseConnection.model.Teacher", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DatabaseConnection.model.TeacherAssignment", b =>
                {
                    b.HasOne("DatabaseConnection.model.ExamSession", "ExamSession")
                        .WithMany("TeacherAssignments")
                        .HasForeignKey("ExamSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DatabaseConnection.model.Teacher", "Teacher")
                        .WithMany("TeacherAssignments")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExamSession");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("DatabaseConnection.model.TeacherConstraint", b =>
                {
                    b.HasOne("DatabaseConnection.model.Teacher", "Teacher")
                        .WithMany("TeacherConstraints")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("DatabaseConnection.model.AssessmentEvent", b =>
                {
                    b.Navigation("AssessmentHandIns");

                    b.Navigation("ExamSessions");
                });

            modelBuilder.Entity("DatabaseConnection.model.Course", b =>
                {
                    b.Navigation("AssessmentEvents");

                    b.Navigation("Classes");

                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("DatabaseConnection.model.ExamSession", b =>
                {
                    b.Navigation("StudentExamAssignments");

                    b.Navigation("TeacherAssignments");
                });

            modelBuilder.Entity("DatabaseConnection.model.PlanningEducationElement", b =>
                {
                    b.Navigation("AssessmentEvent")
                        .IsRequired();
                });

            modelBuilder.Entity("DatabaseConnection.model.Room", b =>
                {
                    b.Navigation("ExamSessions");
                });

            modelBuilder.Entity("DatabaseConnection.model.Schedule", b =>
                {
                    b.Navigation("ExamDays");

                    b.Navigation("ExamSessions");

                    b.Navigation("ScheduleReviews");
                });

            modelBuilder.Entity("DatabaseConnection.model.Student", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("StudentExamAssignment");
                });

            modelBuilder.Entity("DatabaseConnection.model.Teacher", b =>
                {
                    b.Navigation("ScheduleReviewss");

                    b.Navigation("TeacherAssignments");

                    b.Navigation("TeacherConstraints");
                });

            modelBuilder.Entity("DatabaseConnection.model.User", b =>
                {
                    b.Navigation("Student");

                    b.Navigation("Teacher");
                });
#pragma warning restore 612, 618
        }
    }
}
