// <auto-generated />
using System;
using DatabaseConnection.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DatabaseConnection.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260929120518_AddNotesToCourse")]
    partial class AddNotesToCourse
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DatabaseConnection.model.Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClassCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CourseId")
                        .HasColumnType("integer");

                    b.Property<string>("CourseOffering")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Semester")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Class");
                });

            modelBuilder.Entity("DatabaseConnection.model.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ECTS")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("SueCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Course");
                });

            modelBuilder.Entity("DatabaseConnection.model.Enrollment", b =>
                {
                    b.Property<int>("ClassId")
                        .HasColumnType("integer");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.HasKey("ClassId", "StudentId");

                    b.HasIndex("StudentId");

                    b.ToTable("Enrollment");
                });

            modelBuilder.Entity("DatabaseConnection.model.Exam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExamFormat")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ExaminerType")
                        .HasColumnType("integer");

                    b.Property<string>("GradingScale")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlanningResponsible")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Prerequisites")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Exam");
                });

            modelBuilder.Entity("DatabaseConnection.model.ExamClass", b =>
                {
                    b.Property<int>("ExamId")
                        .HasColumnType("integer");

                    b.Property<int>("ClassId")
                        .HasColumnType("integer");

                    b.HasKey("ExamId", "ClassId");

                    b.HasIndex("ClassId");

                    b.ToTable("ExamClass");
                });

            modelBuilder.Entity("DatabaseConnection.model.ExamDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ExaminerType")
                        .HasColumnType("integer");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("integer");

                    b.Property<bool>("Useable")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ScheduleId");

                    b.ToTable("ExamDay");
                });

            modelBuilder.Entity("DatabaseConnection.model.ExamHandIn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ExamId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("HandInDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("HandInTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Part")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExamId");

                    b.ToTable("ExamHandIn");
                });

            modelBuilder.Entity("DatabaseConnection.model.ExamLecturer", b =>
                {
                    b.Property<int>("ExamId")
                        .HasColumnType("integer");

                    b.Property<int>("LecturerId")
                        .HasColumnType("integer");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ExamId", "LecturerId");

                    b.HasIndex("LecturerId");

                    b.ToTable("ExamLecturer");
                });

            modelBuilder.Entity("DatabaseConnection.model.ExamSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExamDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ExamId")
                        .HasColumnType("integer");

                    b.Property<bool>("Locked")
                        .HasColumnType("boolean");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("integer");

                    b.Property<int>("SessionType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExamId");

                    b.HasIndex("ScheduleId");

                    b.ToTable("ExamSession");
                });

            modelBuilder.Entity("DatabaseConnection.model.ExamSessionRoom", b =>
                {
                    b.Property<int>("ExamSessionId")
                        .HasColumnType("integer");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer");

                    b.HasKey("ExamSessionId", "RoomId");

                    b.HasIndex("RoomId");

                    b.ToTable("ExamSessionRoom");
                });

            modelBuilder.Entity("DatabaseConnection.model.Lecturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Initials")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserAccountId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserAccountId")
                        .IsUnique();

                    b.ToTable("Lecturer");
                });

            modelBuilder.Entity("DatabaseConnection.model.LecturerConstraint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ConstraintDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ConstraintType")
                        .HasColumnType("integer");

                    b.Property<int>("LecturerId")
                        .HasColumnType("integer");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LecturerId");

                    b.ToTable("LecturerConstraint");
                });

            modelBuilder.Entity("DatabaseConnection.model.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Campus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<string>("RoomCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Room");
                });

            modelBuilder.Entity("DatabaseConnection.model.ScheduleReview", b =>
                {
                    b.Property<int>("LecturerId")
                        .HasColumnType("integer");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("integer");

                    b.Property<bool>("Approved")
                        .HasColumnType("boolean");

                    b.Property<bool>("Completed")
                        .HasColumnType("boolean");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LecturerId", "ScheduleId");

                    b.HasIndex("ScheduleId");

                    b.ToTable("ScheduleReview");
                });

            modelBuilder.Entity("DatabaseConnection.model.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserAccountId")
                        .HasColumnType("integer");

                    b.Property<int>("ViaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserAccountId")
                        .IsUnique();

                    b.ToTable("Student");
                });

            modelBuilder.Entity("DatabaseConnection.model.StudentExamAssignment", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.Property<int>("ExamId")
                        .HasColumnType("integer");

                    b.Property<bool>("ExtraTime")
                        .HasColumnType("boolean");

                    b.HasKey("StudentId", "ExamId");

                    b.HasIndex("ExamId");

                    b.ToTable("StudentExamAssignment");
                });

            modelBuilder.Entity("DatabaseConnection.model.UserAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("userRole")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("UserAccount");
                });

            modelBuilder.Entity("Schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Approved")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("version")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Schedule");
                });

            modelBuilder.Entity("DatabaseConnection.model.Class", b =>
                {
                    b.HasOne("DatabaseConnection.model.Course", "Course")
                        .WithMany("Classes")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("DatabaseConnection.model.Enrollment", b =>
                {
                    b.HasOne("DatabaseConnection.model.Class", "Class")
                        .WithMany("Enrollments")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DatabaseConnection.model.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("DatabaseConnection.model.ExamClass", b =>
                {
                    b.HasOne("DatabaseConnection.model.Class", "Class")
                        .WithMany("ExamClasses")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DatabaseConnection.model.Exam", "Exam")
                        .WithMany("ExamClasses")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Exam");
                });

            modelBuilder.Entity("DatabaseConnection.model.ExamDay", b =>
                {
                    b.HasOne("Schedule", "Schedule")
                        .WithMany("ExamDays")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("DatabaseConnection.model.ExamHandIn", b =>
                {
                    b.HasOne("DatabaseConnection.model.Exam", "Exam")
                        .WithMany("ExamHandIns")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exam");
                });

            modelBuilder.Entity("DatabaseConnection.model.ExamLecturer", b =>
                {
                    b.HasOne("DatabaseConnection.model.Exam", "Exam")
                        .WithMany("ExamLecturers")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DatabaseConnection.model.Lecturer", "Lecturer")
                        .WithMany("ExamLecturers")
                        .HasForeignKey("LecturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exam");

                    b.Navigation("Lecturer");
                });

            modelBuilder.Entity("DatabaseConnection.model.ExamSession", b =>
                {
                    b.HasOne("DatabaseConnection.model.Exam", "Exam")
                        .WithMany("ExamSessions")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Schedule", "Schedule")
                        .WithMany("ExamSessions")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exam");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("DatabaseConnection.model.ExamSessionRoom", b =>
                {
                    b.HasOne("DatabaseConnection.model.ExamSession", "ExamSession")
                        .WithMany("ExamSessionRooms")
                        .HasForeignKey("ExamSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DatabaseConnection.model.Room", "Room")
                        .WithMany("ExamSessionRooms")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExamSession");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("DatabaseConnection.model.Lecturer", b =>
                {
                    b.HasOne("DatabaseConnection.model.UserAccount", "UserAccount")
                        .WithOne("LecturerAccount")
                        .HasForeignKey("DatabaseConnection.model.Lecturer", "UserAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("DatabaseConnection.model.LecturerConstraint", b =>
                {
                    b.HasOne("DatabaseConnection.model.Lecturer", "Lecturer")
                        .WithMany("LecturerConstraints")
                        .HasForeignKey("LecturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lecturer");
                });

            modelBuilder.Entity("DatabaseConnection.model.ScheduleReview", b =>
                {
                    b.HasOne("DatabaseConnection.model.Lecturer", "Lecturer")
                        .WithMany("ScheduleReviews")
                        .HasForeignKey("LecturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Schedule", "Schedule")
                        .WithMany("ScheduleReviews")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lecturer");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("DatabaseConnection.model.Student", b =>
                {
                    b.HasOne("DatabaseConnection.model.UserAccount", "UserAccount")
                        .WithOne("StudentAccount")
                        .HasForeignKey("DatabaseConnection.model.Student", "UserAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("DatabaseConnection.model.StudentExamAssignment", b =>
                {
                    b.HasOne("DatabaseConnection.model.Exam", "Exam")
                        .WithMany("StudentExamAssignments")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DatabaseConnection.model.Student", "Student")
                        .WithMany("ExamAssignments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exam");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("DatabaseConnection.model.Class", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("ExamClasses");
                });

            modelBuilder.Entity("DatabaseConnection.model.Course", b =>
                {
                    b.Navigation("Classes");
                });

            modelBuilder.Entity("DatabaseConnection.model.Exam", b =>
                {
                    b.Navigation("ExamClasses");

                    b.Navigation("ExamHandIns");

                    b.Navigation("ExamLecturers");

                    b.Navigation("ExamSessions");

                    b.Navigation("StudentExamAssignments");
                });

            modelBuilder.Entity("DatabaseConnection.model.ExamSession", b =>
                {
                    b.Navigation("ExamSessionRooms");
                });

            modelBuilder.Entity("DatabaseConnection.model.Lecturer", b =>
                {
                    b.Navigation("ExamLecturers");

                    b.Navigation("LecturerConstraints");

                    b.Navigation("ScheduleReviews");
                });

            modelBuilder.Entity("DatabaseConnection.model.Room", b =>
                {
                    b.Navigation("ExamSessionRooms");
                });

            modelBuilder.Entity("DatabaseConnection.model.Student", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("ExamAssignments");
                });

            modelBuilder.Entity("DatabaseConnection.model.UserAccount", b =>
                {
                    b.Navigation("LecturerAccount");

                    b.Navigation("StudentAccount");
                });

            modelBuilder.Entity("Schedule", b =>
                {
                    b.Navigation("ExamDays");

                    b.Navigation("ExamSessions");

                    b.Navigation("ScheduleReviews");
                });
#pragma warning restore 612, 618
        }
    }
}
